# ใช้โหมด node_modules ปกติ (Nuxt ยังไม่รองรับ PnP ดีพอ)
nodeLinker: node-modules

# ปิด global cache เพื่อเลี่ยงปัญหา pnpapi ซ้ำกัน
enableGlobalCache: false

# เก็บ dependencies ตามโปรเจกต์ ไม่ปนกับ global
# nmMode: hardlinks-local

# ให้ Yarn ใช้ Corepack manage เวอร์ชัน
# yarnPath: .yarn/releases/yarn-4.10.3.cjs

# เปิด telemetry off (กัน noise)
enableTelemetry: false
